name: Nix Build
on:
  push:
    branches: master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    # Clone project
    - uses: actions/checkout@v2.4.0

    # Install Nix
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    # Setup Cachix
    - uses: cachix/cachix-action@v10
      with:
        name: digitallyinduced

    # Build project
    - working-directory: ./web
      run: |
        nix-build
      
    # Echo
    - working-directory: ./web
      run: nix-shell --run "echo OK"
